version: '3.8'

services:
  polkadot-node:
    container_name: polkadot-overview-polkadot-node
    image: parity/polkadot:latest
    user: root
    volumes:
      - '.chain-data:/root/.local/share/polkadot'
    command: --chain polkadot --pruning archive --wasm-execution Compiled --db paritydb --unsafe-ws-external --rpc-cors all
  mongo:
    container_name: polkadot-overview-mongo
    image: mongo
    user: root
    volumes:
      - '.mongo-data:/data/db'
  polkadot-overview-app:
    container_name: polkadot-overview-app
    image: polkadot-overview-app:production
    build:
      context: .
      args:
        ENVIRONMENT: 'production'
    volumes:
      - .:/usr/src/polkadot-overview
      - /usr/src/polkadot-overview/node_modules
      - /usr/src/polkadot-overview/api/node_modules
      - /usr/src/polkadot-overview/parser-light/node_modules
      - /usr/src/polkadot-overview/ui/node_modules
    ports:
      - "3001:3001"
      - "4001:4001"
